version: "3"  # optional since v1.27.0

services: # Container Define
  nginx:  # Container Name
    container_name: nginx
    build: requirements/nginx/  # Path where Dockerfile exists
    ports: # Public Port Define: [Hosts Port]:[Container Port]
      - "443:443"
    depends_on:
      - wordpress
    restart: always
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_data:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bahn
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress
    restart: always

  # mariadb:
  #   container_name: mariadb
  #   build: requirements/mariadb/
  #   ports:
  #     -"3306:3306"
  #   volumes:
  #     - "db_data:var/lib/mysql"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 0000
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: bahn
  #     MYSQL_PASSWORD: 1234


volumes:
  db_data: {}
  wordpress_data: {}