version: "3"

networks:
  inception-network:
    driver: bridge

volumes:
  mariadb_data:
    driver_opts:
      device: $HOME/data/mariadb_data
      type: none
      o: bind

  wordpress_data:
    driver_opts:
      device: $HOME/data/wordpress_data
      type: none
      o: bind

services: # Container Define
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception-network
    ports: # Public Port Define: [Hosts Port]:[Container Port]
      - 3306:3306
    volumes: # Mount [Hosts Path]:[Container Path]
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    # environment:
      # - MARIADB_DATABASE=$${MARIADB_DATABASE}
      # - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      # - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # - MARIADB_USER=${MARIADB_USER}
      # - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: "no"
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception-network
    ports: # Public Port Define: [Hosts Port]:[Container Port]
      - 9000:9000
    volumes: # Mount [Hosts Path]:[Container Path]
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: "no"

  nginx:  # Container Name
    container_name: nginx
    build: requirements/nginx  # Path where Dockerfile exists
    depends_on:
      - wordpress
    ports: # Public Port Define: [Hosts Port]:[Container Port]
      - 443:443
    networks:
      - inception-network
    volumes: # Mount [Hosts Path]:[Container Path]
      - wordpress_data:/var/www/html
    restart: "no"
  