version: "3.5"  # optional since v1.27.0

networks:
  inception-network:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: $HOME/data/mariadb_data
      type: volume
      o: bind

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: $HOME/data/wordpress_data
      type: volume
      o: bind

services: # Container Define
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    # environment:
    #   MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    #   MARIADB_DATABASE: ${MARIADB_DATABASE}
    #   MARIADB_USER: ${MARIADB_USER}
    #   MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - inception-network
    restart: always
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    # environment:
    #   WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    #   WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    #   WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    #   WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - inception-network
    depends_on:
      - mariadb
    
    restart: always

  nginx:  # Container Name
    container_name: nginx
    build: requirements/nginx  # Path where Dockerfile exists
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports: # Public Port Define: [Hosts Port]:[Container Port]
      - 443:443
    networks:
      - inception-network
    restart: always
  