------------------------------------------
-- MariaDB Initialization for WordPress --
------------------------------------------

-- DB 생성
CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;

-- 일반 계정 생성
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'localhost' IDENTIFIED BY '$MARIADB_PASSWORD';
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';

-- 관리자 계정 생성
CREATE USER IF NOT EXISTS '$MARIADB_ADMIN'@'localhost' IDENTIFIED BY '$MARIADB_ADMIN_PASSWORD';
CREATE USER IF NOT EXISTS '$MARIADB_ADMIN'@'%' IDENTIFIED BY '$MARIADB_ADMIN_PASSWORD';

-- 계정 추가에 대한 변경사항 적용, 반영
FLUSH PRIVILEGES;

-- 일반 계정의 DB 접근 권한 부여
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'localhost' IDENTIFIED BY '$MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';

-- 관리자 계정의 DB 접근 권한 부여
GRANT ALL PRIVILEGES ON *.* TO '$MARIADB_ADMIN'@'localhost' IDENTIFIED BY '$MARIADB_ADMIN_PASSWORD' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO '$MARIADB_ADMIN'@'%' IDENTIFIED BY '$MARIADB_ADMIN_PASSWORD' WITH GRANT OPTION;

ALTER USER root@localhost IDENTIFIED VIA mysql_native_password;
SET PASSWORD = PASSWORD('$MARIADB_ROOT_PASSWORD');

SHOW DATABASES;

USE $MARIADB_DATABASE; SHOW TABLES;

SELECT user, host, password, authentication_string, plugin FROM mysql.user;
